### ISSUE TITLE
Repack dll

### ISSUE THREAD

**Issue by timea-techgirl** [jakev/xamarin-assembly-store-unpack#1]
Hello, thanks for the awesome tool, helps a lot. I'm interested in converting it back to LZ4 and repacking the modified dll into assemblies.blob

Can you please add this feature?

An interesting read here:
https://stackoverflow.com/questions/72689284/compress-xamarin-android-apk-assemblies

**Comment by jakev** [comment]
This should be added with the new commit here: https://github.com/jakev/pyxamstore/commit/87d91f567fb0af9f5fddb492bb64d299be05724d. Do you mind testing to see if it covers what you're looking for? I can close it if this commit works!

**Comment by timea-techgirl** [comment]
Everything works great! 👍🏻
