### ISSUE TITLE
 Abort message: 'Compressed assembly '<assembly_store>' is larger than when the application was built (expected at most 1998848, got 4359976). Assemblies don't grow just like that!'

### ISSUE THREAD

**Issue by NRTnarathip** [jakev/xamarin-assembly-store-unpack#15]
Hi, currently i want replace original System.Core.PrivateLib.dll in file size: 1998848 byte
![image](https://github.com/user-attachments/assets/df9f156a-6023-4243-b0a1-67bc1fd7f670)

and here new dll replacement file size: 4359976 byte
![image](https://github.com/user-attachments/assets/5bdff20b-7e64-4463-a207-1dd99c270e52)

and i when i click play game, i got error log 
![image](https://github.com/user-attachments/assets/efa9da65-8fcf-4cef-b21a-add3c6999c67)

so, how can; i replacement dll, or trick modify it
thanks you❤️

**Comment by qls-api** [comment]
Did you solve this problem?

**Comment by NRTnarathip** [comment]
@qls-api i forgot, sorry
