### ISSUE TITLE
Crash with FileNotFound exception

### ISSUE THREAD

**Issue by Gorge123** [jakev/xamarin-assembly-store-unpack#4]
Script crashed when extracted file has subdir in path. 
Im solved this by adding makedirs command:
print("Extracting %s..." % entry.name)
 
**os.makedirs(os.path.dirname(out_file), exist_ok=True)**

wfile = open(out_file, "wb")

Don't tried repack feature )

**Comment by jakev** [comment]
Are you able to share the APK that's causing the issues?

**Comment by Gorge123** [comment]
https://play.google.com/store/apps/details?id=com.ups.mobile.android

**Comment by jakev** [comment]
Thank you - I see what's going on here. I'll roll this into the next push. Still working on refactoring to make the `pack` command work, but `unpack` should support this + architecture specific assemblies once I push.

**Comment by jakev** [comment]
@Gorge123 can you test with the latest commits on master? This should work now. Thanks for the help!

**Comment by Gorge123** [comment]
> @Gorge123 can you test with the latest commits on master? This should work now. Thanks for the help!
works good now )

**Comment by jakev** [comment]
Great, thanks!
