### ISSUE TITLE
No package metadata was found for pyxamstore

### ISSUE THREAD

**Issue by fripsy** [jakev/xamarin-assembly-store-unpack#5]
Trying to unpack an assembly on Ubuntu 22.04 with Python3 gives me the following error:

Traceback (most recent call last):
  File "/usr/local/bin/pyxamstore", line 33, in <module>
    sys.exit(load_entry_point('pyxamstore==1.0.0', 'console_scripts', 'pyxamstore')())
  File "/usr/local/bin/pyxamstore", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pyxamstore

Unfortunaly this a private apk, so I can not share it.
Any ideas on where I should start to look?

Thanks.

**Comment by jakev** [comment]
Hi @fripsy - Unfortunately old habits die hard and there's a lot of py2 code in the project. I'll start making the project more compatible once I fix the functionality related bugs.

In the meantime perhaps try using virtualenv and forcing py2?

Something like this should work:

```
 cd pyxamstore/
 python2 -m virtualenv venv
 . venv/bin/activate
 python setup.py install
 pyxamstore -h
```

**Comment by jakev** [comment]
This appears to be related to Python3.10, and my current install of Py3 is 3.6. I'll have to look into what's going on here, but the latest commits should bring support to at least 3.6: https://github.com/jakev/pyxamstore/commit/96d14b88c8f095e15129c2f8a4aeea6daba94183

**Comment by jakev** [comment]
Sorry for the delay. Is there something unusual about your python installation? The latest pyxamstore code works fine with Py3.10 in a venv:

```
python3.10 -m venv venv3.10
. venv3.10/bin/activate
python setup.py install
cd test/jvxam/
pyxamstore unpack -d unknown/assemblies/
pyxamstore pack
```

I will look into moving the code away from `setup.py`, since it appears that's been deprecated :)

**Comment by fripsy** [comment]
No problem, don't have much time myself ;-)
Been using it with the venv in Python2, works like a charm...

Could very well be my installation, I'm switching computers next week, will try on the new one when everything is setup.
Thanks!

**Comment by jpstotz** [comment]
Thanks, works fine using Python3.11. I only had up upgrade the requirements as the old xxhash version had no wheel for Windows.

I am now using these requirements:
```
future==0.18.3
lz4==4.3.2
xxhash==3.2.0
```

**Comment by jakev** [comment]
I updated the pip requirements to support the versions above: https://github.com/jakev/pyxamstore/commit/23cd52612702d08495570f96f60883d6047ae429

I'm closing this issue :)
