### ISSUE TITLE
Functions for compressing and uncompressing a single DLL?

### ISSUE THREAD

**Issue by TerminalCalm** [jakev/xamarin-assembly-store-unpack#6]
First off, thanks for the great tool.

Second, would it be possible to uncompress, edit, and compress a single Xamarin dll with this? And if not, what would be needed to do so? I have an apk I need to do some minor edits to, but the apk contains no .blob -- I think it was generated just before that change was made to Xamarin. All I need to do is edit a few strings, but so far I haven't been able to figure out how to compress the relevant dll after I've uncompressed it and made my edits, so I'm hoping this tool can get me over that finish line, with or without a modification. I've tried modding it myself but I think I'm missing a key bit of info.

**Comment by jakev** [comment]
Hi! Would you be able to share the APK you're working with?

**Comment by TerminalCalm** [comment]
Hey there. Unfortunately I can't -- not mine to share.

However, I ultimately found out that recompressing the Dll wasn't necessary -- apparently once it's uncompressed, it can stay that way, be compiled into the apk again, and everything is fine. But I admit I was never able to decompress, edit the dll, then recompress it again in a way that didn't throw errors once the app was run on an Android device. As in I checked the log via adb and it errored out on the decompression attempt.

I guess it's moot for most people since the .blob change is now the way everything is handled, so thanks again for the great tool and pardon my cluttering up your issues section!

**Comment by jakev** [comment]
Sounds good! Sorry for the delay and glad you got it working. If you really wanted to know how the DLLs get compressed with Xamarin, check this short function: https://github.com/jakev/pyxamstore/blob/master/pyxamstore/explorer.py#L336
