### ISSUE TITLE
failed to create process.

### ISSUE THREAD

**Issue by WisnuNug** [jakev/xamarin-assembly-store-unpack#8]
I've installed the requitment for pyxamstore, and it's installed successfully in python.
but when i call tool. always appears failed to create process.

**Comment by jakev** [comment]
Hello! Can you share the output of running the tool? In addition, can you share which platform you're running the tool from (Windows, Linux, Mac)?

**Comment by WisnuNug** [comment]
> Hello! Can you share the output of running the tool? In addition, can you share which platform you're running the tool from (Windows, Linux, Mac)?

Im sorry, I using win 10 64bit. I have installed all requitment python but when start tool
Microsoft Windows [Version 10.0.19045.2965]
(c) Microsoft Corporation. All rights reserved.

C:\pyxamstore>pyxamstore
failed to create process.

**Comment by WisnuNug** [comment]
omg, Im wrong. I try uninstalling python and install to another path. is worked!
and solved, thank you bro.
